#!/bin/sh -e
# set up mdev for an initrd
PREREQS=""
case "$1" in
    prereqs)
    echo "$PREREQS"
    exit 0
    ;;
esac

# if udevadm is executeable, don't run (let udev run)
[ ! -x /sbin/udevadm ] || exit 0

modprobe -abq sd_mod
# try both old and new names
[ -w /proc/sys/kernel/hotplug ] &&  \
    echo "/sbin/mdev" >/proc/sys/kernel/hotplug || true
[ -w /sys/kernel/uevent_helper ] && \
    echo "/sbin/mdev" >/sys/kernel/uevent_helper || true
mdev -s
grep -h MODALIAS /sys/bus/*/devices/*/uevent 2>/dev/null | \
	cut -d= -f2 |xargs modprobe -abq
[ -z "$ROOTDELAY" ] || sleep "${ROOTDELAY}"
